# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Biostatistics 776 - Statistical Computing
email: rdpeng@jhu.edu
description: This the web site for Biostatistics 776 - Statistical Computing at the Johns Hopkins Bloomberg School of Public Health
baseurl: "/Biostat776" # the subpath of your site, e.g. /blog
url: "http://rdpeng.github.io/Biostat776" # the base hostname & protocol for your site
twitter_username: rdpeng
github_username:  rdpeng

# Build settings
markdown: kramdown
theme: minima
